brand_name:
  default: ""
website_url:
  default: ""
logo_url:
  default: ""
mobile_logo_url:
  default: ""
logo_title_text:
  default: ""
  description: "'title' attribute for the logo link, usually appears as a tooltip. Defaults to brand_name."
links:
  type: list
  list_type: simple
  default: ""
  description: "Format: name,url,target (optional),title_attribute (optional)"
icons:
  type: list
  list_type: simple
  default: ""
  description: "Format: icon-name,url,target (optional),title_attribute (optional)"
custom_font_awesome_icons:
  type: list
  list_type: simple
  default: ""
  description: "List of FontAwesome 5 icons used in this theme component"
show_bar_on_mobile:
  type: bool
  default: false
